/**
 * Starling Bank Personal API helper
 * Uses Personal Access Token (generated by user at developer.starlingbank.com)
 * API docs: https://developer.starlingbank.com/docs
 */

import { z } from 'zod'
import { logger } from './logger'

const STARLING_BASE = 'https://api.starlingbank.com/api/v2'

// ─── Response schemas ─────────────────────────────────────────────────────────

const StarlingAccountSchema = z.object({
  accountUid: z.string(),
  accountType: z.string(),
  name: z.string().default(''),
  currency: z.string(),
  createdAt: z.string(),
})

const StarlingAccountsResponseSchema = z.object({
  accounts: z.array(StarlingAccountSchema).default([]),
})

const StarlingBalanceSchema = z.object({
  clearedBalance: z.object({ minorUnits: z.number(), currency: z.string() }),
  effectiveBalance: z.object({ minorUnits: z.number(), currency: z.string() }),
})

const StarlingTransactionSchema = z.object({
  feedItemUid: z.string(),
  categoryUid: z.string(),
  amount: z.object({ minorUnits: z.number(), currency: z.string() }),
  sourceAmount: z.object({ minorUnits: z.number(), currency: z.string() }),
  direction: z.enum(['IN', 'OUT']),
  updatedAt: z.string(),
  transactionTime: z.string(),
  settlementTime: z.string().optional(),
  source: z.string(),
  status: z.string(),
  counterPartyType: z.string(),
  counterPartyName: z.string(),
  reference: z.string().optional(),
  country: z.string(),
  spendingCategory: z.string(),
  userNote: z.string().optional(),
})

const StarlingFeedResponseSchema = z.object({
  feedItems: z.array(StarlingTransactionSchema).default([]),
})

export type StarlingAccount = {
  accountUid: string
  accountType: string
  name: string
  currency: string
  createdAt: string
}

export type StarlingBalance = {
  clearedBalance: { minorUnits: number; currency: string }
  effectiveBalance: { minorUnits: number; currency: string }
}

export type StarlingTransaction = {
  feedItemUid: string
  categoryUid: string
  amount: { minorUnits: number; currency: string }
  sourceAmount: { minorUnits: number; currency: string }
  direction: 'IN' | 'OUT'
  updatedAt: string
  transactionTime: string
  settlementTime?: string
  source: string
  status: string
  counterPartyType: string
  counterPartyName: string
  reference?: string
  country: string
  spendingCategory: string
  userNote?: string
}

export type StarlingSpace = {
  savingsGoalUid: string
  name: string
  currency: string
  target?: { minorUnits: number; currency: string }
  totalSaved: { minorUnits: number; currency: string }
}

function pence(minorUnits: number): number {
  return minorUnits / 100
}

async function starlingFetch(token: string, path: string) {
  const res = await fetch(`${STARLING_BASE}${path}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/json',
    },
  })
  if (!res.ok) throw new Error(`Starling API ${path} → ${res.status}`)
  return res.json()
}

export async function getStarlingAccounts(token: string): Promise<StarlingAccount[]> {
  const raw = await starlingFetch(token, '/accounts')
  const parsed = StarlingAccountsResponseSchema.safeParse(raw)
  if (!parsed.success) {
    logger.warn({ validationError: parsed.error.message }, '[starling] getStarlingAccounts response failed schema validation')
    return []
  }
  return parsed.data.accounts
}

export async function getStarlingBalance(
  token: string,
  accountUid: string
): Promise<StarlingBalance> {
  const raw = await starlingFetch(token, `/accounts/${accountUid}/balance`)
  const parsed = StarlingBalanceSchema.safeParse(raw)
  if (!parsed.success) {
    throw new Error(`Starling balance response invalid: ${parsed.error.message}`)
  }
  return parsed.data
}

export async function getStarlingSavingsSpaces(
  token: string,
  accountUid: string
): Promise<StarlingSpace[]> {
  const data = await starlingFetch(token, `/account/${accountUid}/savings-goals`)
  return data.savingsGoalList ?? []
}

export async function getStarlingTransactions(
  token: string,
  accountUid: string,
  categoryUid: string,
  from: Date,
  to: Date
): Promise<StarlingTransaction[]> {
  const params = new URLSearchParams({
    minTransactionTimestamp: from.toISOString(),
    maxTransactionTimestamp: to.toISOString(),
  })
  const raw = await starlingFetch(
    token,
    `/feed/account/${accountUid}/category/${categoryUid}?${params}`
  )
  const parsed = StarlingFeedResponseSchema.safeParse(raw)
  if (!parsed.success) {
    logger.warn({ validationError: parsed.error.message }, '[starling] getStarlingTransactions response failed schema validation')
    return []
  }
  return parsed.data.feedItems
}

/** Map Starling's spendingCategory to a human-readable name for auto-categorisation bootstrap */
export const STARLING_CATEGORY_MAP: Record<string, string> = {
  EATING_OUT: 'eating out',
  GROCERIES: 'groceries',
  TRANSPORT: 'transport',
  ENTERTAINMENT: 'entertainment',
  SHOPPING: 'shopping',
  HEALTH: 'health & fitness',
  BILLS_AND_SERVICES: 'bills & utilities',
  SAVING: 'savings',
  INCOME: 'salary',
  PAYMENTS: 'other',
  GENERAL: 'other',
  CHARITY: 'other',
  HOLIDAYS: 'entertainment',
  FAMILY: 'other',
  PERSONAL_CARE: 'health & fitness',
  HOME: 'bills & utilities',
  PETS: 'other',
  VEHICLES: 'transport',
  EDUCATION: 'other',
}

/** Sync one Starling account into the moducore DB */
export async function syncStarlingAccount(
  db: import('@moducore/db').DbClient,
  tenantId: string,
  dbAccountId: string,
  token: string,
  accountUid: string
): Promise<{ synced: number }> {
  const {
    bulkUpsertTransactions, suggestCategory,
    updateAccount, getCategories,
  } = await import('@moducore/db')

  // Fetch last 90 days of transactions
  const to = new Date()
  const from = new Date(to)
  from.setDate(from.getDate() - 90)

  // Get the main category UID (default spending category for the account)
  const accountsData = await starlingFetch(token, `/accounts`)
  const account = (accountsData.accounts as StarlingAccount[]).find(
    (a) => a.accountUid === accountUid
  )
  if (!account) return { synced: 0 }

  // Starling uses categoryUid = accountUid for the main feed
  const txns = await getStarlingTransactions(token, accountUid, accountUid, from, to)
  const allCategories = await getCategories(db, tenantId)

  const rows = await Promise.all(
    txns
      .filter((t) => t.status === 'SETTLED')
      .map(async (t) => {
        const amountGBP = pence(t.amount.minorUnits)
        const amount = t.direction === 'IN' ? String(amountGBP) : String(-amountGBP)
        const merchant = t.counterPartyName
        const date = t.transactionTime.slice(0, 10)

        // Try merchant rules first, then fall back to Starling's category
        let categoryId = await suggestCategory(db, tenantId, merchant)
        if (!categoryId) {
          const catName = STARLING_CATEGORY_MAP[t.spendingCategory]?.toLowerCase()
          if (catName) {
            const match = allCategories.find((c) => c.name.toLowerCase() === catName)
            if (match) categoryId = match.id
          }
        }

        return {
          accountId: dbAccountId,
          amount,
          description: t.reference ?? merchant,
          merchant,
          categoryId: categoryId ?? undefined,
          categoryConfirmed: false,
          date,
          source: 'starling_import' as const,
          externalId: t.feedItemUid,
        }
      })
  )

  const inserted = await bulkUpsertTransactions(db, tenantId, rows)

  // Update last synced timestamp
  await updateAccount(db, tenantId, dbAccountId, { starlingLastSyncedAt: new Date() })

  return { synced: inserted.length }
}
